Reading
ChanKyeol/silhakdan pull request #7
Opened 2021-11-29 16:17 UTC by ChanKyeol

더 간추려서 적겠습니다.

2021-11-29 16:25 UTC, coldMater commented
먼저 PR 이름이 직관적이지 않네요. 챕터1, 챕터2 완료 라고 해보는건 어떤가요?

2021-11-29 16:26 UTC, ChanKyeol commented
어디서 바꾸나요

2021-11-29 16:27 UTC, coldMater commented
> 어디서 바꾸나요

오른쪽 위 Edit 있습니다.

2021-11-29 16:27 UTC, coldMater commented
좋습니다. 사실 이 PR 은 이슈를 처리한 PR 입니다. 이 이야기 이해 되시나요?
그렇다면 어떤 이슈를 처리한 Pr 인가요?

2021-11-29 16:29 UTC, ChanKyeol commented
챕터1과 2를 적었습니다.

2021-11-29 16:30 UTC, coldMater commented
이슈는 여기 있습니다. https://github.com/ChanKyeol/silhakdan/issues

2021-11-29 16:31 UTC, ChanKyeol commented
PART1 / 1장 어떤 개발자가 될 것인가?

2021-11-29 16:33 UTC, coldMater commented
ㅋㅋ 이슈를 공유할 때는 해당 이슈의 링크를 공유해주시면 됩니다.

2021-11-29 16:34 UTC, ChanKyeol commented
https://github.com/ChanKyeol/silhakdan/issues/3

2021-11-29 16:34 UTC, coldMater commented
그리고 이슈는 1장, 2장 해결하신거 아닌가요?

2021-11-29 16:36 UTC, coldMater commented
깃헙에서는 이슈를 # 으로 구분합니다. # 을 입력하면 자동완성 할 수 있는 창이 뜰거에요. 
이 PR 에서 관련된 해당 이슈를 선택해주시면 됩니다.

2021-11-29 16:36 UTC, ChanKyeol commented
#3

2021-11-29 16:36 UTC, coldMater commented
제목에 넣어보세요.

2021-11-29 16:38 UTC, coldMater commented
제목에는 안들어가나 보군요. 본문에 넣어보세요.

2021-11-29 16:40 UTC, coldMater commented
#4 이것도 해결하신거 아닌가요? ㅎㅎ...

2021-11-29 16:41 UTC, ChanKyeol commented
노우 거기 가려면 멀었어요

2021-11-29 16:42 UTC, coldMater commented
이슈 제목 잘 보세요 ㅋㅋㅋ

2021-11-29 16:42 UTC, coldMater commented
그리고 이슈 아마 제 생각에는 덜만드신것 같습니다.

2021-11-29 16:42 UTC, ChanKyeol commented
아 이슈는 아직 안만들었네용

2021-11-29 16:44 UTC, coldMater requested changes

2021-11-29 16:44 UTC, coldMater commented on reading/오늘부터개발자!/chapter1.md
> +-   데이터 사이언티스트 : 쌓여진 데이터를 활용가는한 데이터로 바꾸는 개발자
이 부분은 삭제하고 아래 내용에 통합하는게 낫지 않을까요?

2021-11-29 16:44 UTC, coldMater commented on reading/오늘부터개발자!/chapter1.md
> +앱 프론트엔드 개발자, 웹 프론트엔드 개발자 우리가 사용하는 웹 또는 앱 사이트의 앞부분을 만드는 개발자, 주로 앞에서 마주하는 부분을 담당함
개발 분야를 각각 unordered list 로 더 간추린다면 시각적으로 훨씬 깔끔할 것 같아요.

2021-11-29 16:56 UTC, coldMater requested changes

2021-11-29 16:56 UTC, coldMater commented on reading/오늘부터개발자!/chapter1.md
> +우리가 이용하는 앱(웹)의 보이는 부분들을 다루는 개발자, 앱 프론트엔드 개발자, 웹 프론트엔드 개발자 우리가 사용하는 웹 또는 앱 사이트의 앞부분을 만드는 개발자, 주로 앞에서 마주하는 부분을 담당함
제 의도가 잘못전달됐네요

여기서 ## 은 그대로 유지하고

각각의 직군에 대한 설명을 unordered list 로 바꾸라는 거였어요. 다음과 같이요.
```suggestion
## 프론트엔드 개발자
- 우리가 이용하는 앱(웹)의 보이는 부분들을 다루는 개발자
- 앱 프론트엔드 개발자, 웹 프론트엔드 개발자 
우리가 사용하는 웹 또는 앱 사이트의 앞부분을 만드는 개발자
- 주로 앞에서 마주하는 부분을 담당함
```

2021-11-29 17:01 UTC, coldMater commented on reading/오늘부터개발자!/chapter2.md
> +회사 초반에는 소규모로 정말 필요한 기능들만 탑재한채로 서비스가 오픈한다. 잘 되는 것은 쉽지 않지만 운이 좋게 입소문들 타고 유명해 진다면 더 좋고 편리한 서비스를 개발해야한다. 이렇게 까지 된다면 한 두명의 개발자로는 부족하고 더욱 많은 개발자가 필요로 한게 된다. 그리고 개발은 한 번에 끝나는 것이 아니기 때문에 큰 규모의 프로젝트를 진행해본 개발자
회사가 성장하고 서비스의 규모가 커짐에 따라 더 많은 경험 있는 개발자를 필요로 하게 된다. 경험 있는 개발자는 많지 않기에, 요즘 대부분의 회사들은 개발자를 상시모집으로 채용하고 있다. 그렇기에 **준비만 되어있다면 언제든 개발자로 취업을 할 수 있는 시대**이다.

요런식으로 뼈대만 최대한 추출해서 써주면 훨씬 간결할 것 같습니다.

2021-11-29 17:03 UTC, ChanKyeol commented on reading/오늘부터개발자!/chapter2.md
> +회사 초반에는 소규모로 정말 필요한 기능들만 탑재한채로 서비스가 오픈한다. 잘 되는 것은 쉽지 않지만 운이 좋게 입소문들 타고 유명해 진다면 더 좋고 편리한 서비스를 개발해야한다. 이렇게 까지 된다면 한 두명의 개발자로는 부족하고 더욱 많은 개발자가 필요로 한게 된다. 그리고 개발은 한 번에 끝나는 것이 아니기 때문에 큰 규모의 프로젝트를 진행해본 개발자
요약 노력하겠습니다

2021-11-29 17:03 UTC, coldMater commented on reading/오늘부터개발자!/chapter1.md
> +-   기존에 쌓여진 데이터를 정제하여 활용가능한 의미있는 데이터로 만드는 역할을 하는 개발자
```suggestion
### 개발자는 유용한 서비스를 만드는 사람들
일반적으로 고객들은 물건을 구매할 때 회원가입 -> 검색 -> 장바구니 -> 결제(쿠폰 적립금 사용) -> 구매확정, 리뷰작성 or 교환, 환불 이정도의 패턴이 전부일 수 있다. 하지만 프로그래밍은 이렇게 간단하지 않다. 보여지는 페이지만해도 메인 페이지, 카테고리 페이지, 상세 페이지, 장바구니 페이지, 결제 페이지 등 여러 개의 페이지들을 구성하고 만들어야한다. 그리고 고객들이 입력한 정보들(주소, 어떤 물건을 주문했는지, 적립금을 얼마나 사용했는지, 어떤 쿠폰을 사용했는지 등)을 데이터 베이스에 저장하거나 수정해야하고 교환, 환불 등 수많은 상황들을 가정하고 모든 경우의 수에 대비해 놓아야한다. 고객들이 보는 편리한 화면에는 수많은 로직들이 있는 것이다.

### 다양한 개발분야
이렇게 단순히 상품 하나를 구매하는 것만 해도 다양한 변수들이 존재한다. 이렇기에 개발은 혼자서는 진행하기 어렵다. 그래서 다양한 분야가 존재한다.

### 프론트엔드 개발자
-   우리가 이용하는 앱(웹)의 보이는 부분들을 다루는 개발자
-   앱 프론트엔드 개발자
-   웹 프론트엔드 개발자 우리가 사용하는 웹 또는 앱 사이트의 앞부분을 만드는 개발자
-   주로 앞에서 마주하는 부분을 담당함

### 백엔드 개발자
-   보이지 않는 부분을 다루는 개발자
-   프론트엔드에서 보내주는 자료들을 처리하는 로직 개발
-   데이터 베이스 설계 등 웹, 앱 페이지 안에서 일어날 수 있는 굉장히 다양한 케이스들을 모두 고려하여야 한다.

### 데브옵스 개발자
-   서비스가 안정적으로 돌아가도록 전체적인 인프라를 만들고 관리하는 개발자
-   서버를 유동적으로 늘렸다 줄였다 하면서 다운되는 일이 없도록 하는 등 서비스가 안정적으로 돌아가도록하는 역할.
-   개발과 운영을 연계하여 다양한 기능들을 설계하고 만드는 개발자.
-   또는 '인프라 개발자'라고도 함(데브옵스 > 인프라)

### 데이터 사이언티스트
-   쌓여진 데이터를 활용가는한 데이터로 바꾸는 개발자
-   기존에 쌓여진 데이터를 정제하여 활용가능한 의미있는 데이터로 만드는 역할을 하는 개발자
```

2021-11-29 17:05 UTC, coldMater commented
여기까지만 수정해보시죠.

2021-11-29 17:11 UTC, coldMater commented on reading/오늘부터개발자!/chapter1.md
> +### 다양한 개발분야
이건 엄밀히 ## 이 맞겠네요. 하위 내용을 포함하기 때문에요.

2021-12-03 15:00 UTC, coldMater approved these changes

2021-12-03 15:02 UTC, merged